name: flutter_stetho_example
description: Demonstrates how to use the flutter_stetho plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  stetho_network_inspector:
    path: ../

flutter:
  uses-material-design: true
