name: stetho_network_inspector
description: A network inspector for Flutter on Android using the Chrome Dev Tools
version: 0.5.2
author: Anil Rao K <anil@anilraok.com>
homepage: https://github.com/anilraok/stetho_network_inspector

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

flutter:
  plugin:
    androidPackage: com.brianegan.flutterstetho
    pluginClass: FlutterStethoPlugin
