name: stetho_network_inspector
description: A network inspector for Flutter on Android using the Chrome Dev Tools
version: 0.5.2
author: Anil Rao K <anil@anilraok.com>
homepage: https://github.com/anilraok/stetho_network_inspector

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platform:
      android:
        package: com.brianegan.flutterstetho
        pluginClass: FlutterStethoPlugin
